### ISSUE TITLE
Appareils desactivés

### ISSUE THREAD

**Issue by mathieugeissler** [Aohzan/ipx800v5#16]
Hello,

J'ai un petit souci avec l'intégration, j'utilise les x4vr et x4fp sans souci depuis pas mal de temps et j'ai voulu intégré un x8r sauf que l'appareil est considéré comme désactivé dans home assistant (tout comme mes autres appareils xdimmer, x24d) alors que tout fonctionne sur l'ipx.

je ne trouve pas comment les activer ?

config :
```
  ipx800v5:
    - name: IPX800 V5
      host: 10.69.4.3
      api_key: *****
      push_password: 1234
      devices_auto:
      - ipx
      - x8r
      - xdimmer
      - x4vr
      - x24d
      - tempo
      - xthl
      - x4fp
      devices:
      - name: Lumière SaM
        ext_type: x8r
        ext_number: 0
        io_number: 1
        component: light
```

![Capture d’écran 2024-05-21 à 18 45 12](https://github.com/Aohzan/ipx800v5/assets/13039638/7a9bec16-583a-4ea1-8927-da0c3b21d7a7)
