### ISSUE TITLE
door opening sensor in NO

### ISSUE THREAD

**Issue by Mickaelclercq** [Aohzan/ipx800v5#4]
hello could you help me I have magnetic door sensors normally closed on an x24d, it returns an erroneous value since they are No, can you explain to me how to change the value (when it is closed the window is  closed and when it is off the window is open) thank you in advance you are doing a great job.

**Comment by Aohzan** [comment]
hi
you can put an IO related with the X24D input with a NOT relation
![image](https://user-images.githubusercontent.com/2736322/187209015-17fc9052-b08f-49fc-a413-9e5180f16529.png)
and add the IO in the home-assistant configuration

or, you can create a template binary_sensor in Home-Assisant and get the state inverted from the ipx800 binary_sensor in the `value_template`, like I do for my garage door:
```yaml
  - platform: template
    covers:
      porte_garage:
        device_class: garage
        friendly_name: "Porte Garage"
        unique_id: "template_cover_porte_garage"
        value_template: "{{ is_state('binary_sensor.etat_porte_garage', 'off') }}"
        open_cover:
          - service: switch.turn_on
            data:
              entity_id: switch.relais_porte_garage
...
```

**Comment by Mickaelclercq** [comment]
being a novice on home assistant can you explain to me how after having created an IO integrated them into home assistant
thank you

**Comment by Mickaelclercq** [comment]
si vous parler francais c'est même plus simple car je parle francais et trés peu anlglais.

**Comment by Aohzan** [comment]
il y a un exemple dans le readme:
```yaml
      - name: Mon Virtual IO
        component: switch
        ext_type: ipx
        type: io
        id: 65703
```
